// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package logic

import (
	"github.com/gogf/gf/cmd/gf/v2/internal/logic/internal"
)

// internalUnitLogic is internal type for wrapping internal DAO implements.
type internalUnitLogic = *internal.UnitLogic

// unitLogic is the data access object for table unit.
// You can define custom methods on it to extend its functionality as you wish.
type unitLogic struct {
	internalUnitLogic
}

var (
	// Unit is globally public accessible object for table unit operations.
	Unit = unitLogic{
		internal.NewUnitLogic(),
	}
)

// Fill with you ideas below.
